### PR TITLE
spelling correction

### PR DESCRIPTION
**Pull request by lazy-engineer100**
on line 11, changes "winow" to "window"

### CODE REVIEW

**Comment by Illya9999** [comment]
Screenshot_20210215-233648_Discord
Lol

**Comment by lazy-engineer100** [comment]
does the "lol" (and the image) mean i did something bad/something you did not want me to do?

**Comment by Picoseconds** [comment]
@Illya9999 Please delete that it was a joke

**Comment by Picoseconds** [comment]
> does the "lol" (and the image) mean that your saying that i did something bad/something you did not want me to do?

@lazy-engineer100 No, that's a joke Discord message from me

**Comment by Illya9999** [comment]
> does the "lol" (and the image) mean that your saying that i did something bad/something you did not want me to do?

no not at all! I just found it funny that my friend called you a vermin and told me to close your PR

**Comment by Picoseconds** [comment]
> > does the "lol" (and the image) mean that your saying that i did something bad/something you did not want me to do?
> 
> no not at all! I just found it funny that my friend called you a vermin and told me to close your PR

it was an obvious joke can you at least censor the name or something idk dude

**Comment by Picoseconds** [comment]
> > does the "lol" (and the image) mean that your saying that i did something bad/something you did not want me to do?
> 
> no not at all! I just found it funny that my friend called you a vermin and told me to close your PR

"friend"

**Comment by lazy-engineer100** [comment]
> no not at all! I just found it funny that my friend called you a vermin and told me to close your PR

does "close" mean to accept the changes for the main branch?
ive had my github account for a while, but i am new to actually *using* it

**Comment by Picoseconds** [comment]
Close means to delete the pull request, which is basically saying it will never be merged.

**Comment by Illya9999** [comment]
> > no not at all! I just found it funny that my friend called you a vermin and told me to close your PR
> 
> does "close" mean to accept the changes for the main branch?
> ive had my github account for a while, but i am new to actually _using_ it
> im also unfamiliar to coding in general (but i am learning) which was why i was not able to do much more that the spelling error

What picoseconds said, and dont learn coding from this repo. It's a display of exceptionally bad coding practices and spaghetti code

**Comment by lazy-engineer100** [comment]
im not planning to learn from here, i just added the letter because when i tried to join my own server to test it i noticed the error and it fixed it

**Pull request merged**
